version: 2.1

orbs:
  aws-ecr: circleci/aws-ecr@8.1.3
  aws-eks: circleci/aws-eks@2.2.0
  kubernetes: circleci/kubernetes@1.3.1

jobs:
  lint-code:
    docker:
      - image: python:3.7.3-stretch
    working_directory: ~/repo
    steps:
      - checkout
      - restore_cache:
          keys:
            - v1-dependencies-{{ checksum "requirements.txt" }}
            - v1-dependencies-
      - run:
          name: install dependencies
          command: |
            python3 -m venv venv
            . venv/bin/activate
            make install
            make install-hadolint
      - save_cache:
          paths:
            - ./venv
          key: v1-dependencies-{{ checksum "requirements.txt" }}
      - run:
          name: run lint
          command: |
            . venv/bin/activate
            make lint

  deploy-app:
    docker:
      - image: 'cimg/base:stable'
    steps:
      - checkout
      - run:
          name: Create deployment template
          command: |
            sed -i "s/__IMAGE_TAG__/${CIRCLE_SHA1:0:7}/g" deployment/deployment.yaml
            cat deployment/deployment.yaml
      - aws-eks/update-kubeconfig-with-authenticator:
          cluster-name: ${EKS_CLUSTER_NAME}
          aws-region: ${AWS_REGION} 
          install-kubectl: true
      - kubernetes/create-or-update-resource:
          resource-file-path: deployment/deployment.yaml
          show-kubectl-command: true
workflows:
  default:
    jobs:
      - lint-code
      - aws-ecr/build-and-push-image:
          requires:
            - lint-code
          name: build-and-push-image
          path: .
          repo: 'udacity-cloud-devops-capstone-project-repo'
          tag: ${CIRCLE_SHA1:0:7}
      - deploy-app:
          requires:
            - build-and-push-image