apiVersion: apps/v1
kind: Deployment
metadata:
  name: project-capstone-deployment
  labels:
    app: project-capstone-app
spec:
  replicas: 2
  selector:
    matchLabels:
      app: project-capstone-app
  template:
    metadata:
      labels:
        app: project-capstone-app
    spec:
      containers:
      - name: app
        image: 007259284529.dkr.ecr.us-east-1.amazonaws.com/udacity-cloud-devops-capstone-project-repo:__IMAGE_TAG__
        ports:
          - name: app
            containerPort: 80
---
apiVersion: v1
kind: Service
metadata:
  name: project-capstone-service
spec:
  selector:
    app: project-capstone-app
  type: LoadBalancer
  ports:
    - protocol: TCP
      port: 80
      targetPort: 80